/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/bmi-calculator`; params?: Router.UnknownInputParams; } | { pathname: `/cardio`; params?: Router.UnknownInputParams; } | { pathname: `/diabetes`; params?: Router.UnknownInputParams; } | { pathname: `/medicine-reminder`; params?: Router.UnknownInputParams; } | { pathname: `/symptoms`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/forgot-password` | `/forgot-password`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/signup` | `/signup`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/blood-banks` | `/blood-banks`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/search` | `/search`; params?: Router.UnknownInputParams; } | { pathname: `/appointments`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } } | { pathname: `/appointments/[doctorId]`, params: Router.UnknownInputParams & { doctorId: string | number; } } | { pathname: `/appointments/[specializationId]`, params: Router.UnknownInputParams & { specializationId: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/bmi-calculator`; params?: Router.UnknownOutputParams; } | { pathname: `/cardio`; params?: Router.UnknownOutputParams; } | { pathname: `/diabetes`; params?: Router.UnknownOutputParams; } | { pathname: `/medicine-reminder`; params?: Router.UnknownOutputParams; } | { pathname: `/symptoms`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/forgot-password` | `/forgot-password`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/signup` | `/signup`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/blood-banks` | `/blood-banks`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/search` | `/search`; params?: Router.UnknownOutputParams; } | { pathname: `/appointments`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } } | { pathname: `/appointments/[doctorId]`, params: Router.UnknownOutputParams & { doctorId: string; } } | { pathname: `/appointments/[specializationId]`, params: Router.UnknownOutputParams & { specializationId: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/bmi-calculator${`?${string}` | `#${string}` | ''}` | `/cardio${`?${string}` | `#${string}` | ''}` | `/diabetes${`?${string}` | `#${string}` | ''}` | `/medicine-reminder${`?${string}` | `#${string}` | ''}` | `/symptoms${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/forgot-password${`?${string}` | `#${string}` | ''}` | `/forgot-password${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/login${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/signup${`?${string}` | `#${string}` | ''}` | `/signup${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/blood-banks${`?${string}` | `#${string}` | ''}` | `/blood-banks${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/profile${`?${string}` | `#${string}` | ''}` | `/profile${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/search${`?${string}` | `#${string}` | ''}` | `/search${`?${string}` | `#${string}` | ''}` | `/appointments${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/bmi-calculator`; params?: Router.UnknownInputParams; } | { pathname: `/cardio`; params?: Router.UnknownInputParams; } | { pathname: `/diabetes`; params?: Router.UnknownInputParams; } | { pathname: `/medicine-reminder`; params?: Router.UnknownInputParams; } | { pathname: `/symptoms`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/forgot-password` | `/forgot-password`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/signup` | `/signup`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/blood-banks` | `/blood-banks`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/search` | `/search`; params?: Router.UnknownInputParams; } | { pathname: `/appointments`; params?: Router.UnknownInputParams; } | `/+not-found` | `/appointments/${Router.SingleRoutePart<T>}` | `/appointments/${Router.SingleRoutePart<T>}` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } } | { pathname: `/appointments/[doctorId]`, params: Router.UnknownInputParams & { doctorId: string | number; } } | { pathname: `/appointments/[specializationId]`, params: Router.UnknownInputParams & { specializationId: string | number; } };
    }
  }
}
